### PR TITLE
Libwda ifbeam update

### PR DESCRIPTION
**Pull request by marcmengel**
This supercedes #4, and gets ifdhc, ifdhc_config, and ifdh_art building something like properly. 
Also adds to pretty much the whole art suite:
* `url_for_version` routines
* patch to do test subdirectories `if(BUILD_TESTING)`
* set compilers from Spack rather than CMakePresets.json
* version entries for recent versions

### CODE REVIEW

**Comment by chissg** [comment]
Marc, `url_for_version()` was deliberately removed as no longer necessary. How far back in Spack versions are we willing to support?

**Comment by marcmengel** [comment]
Without url_for_version you cannot even checksum a new version.   I don't think we want to be git cloning tags to build releases, we want them built from checksummed tarballs.

**Comment by chissg** [comment]
> Without url_for_version you cannot even checksum a new version. I don't think we want to be git cloning tags to build releases, we want them built from checksummed tarballs.

Very confused, as this does not jibe with my remembered experience. can this wait until I return on 2023-01-09?

**Review by greenc-FNAL — APPROVED** [review]
Sorry for delay due to vacation. After review, I have no idea how I decided that `url_for_version()` was no longer necessary.

Everything looks good to merge.

**Comment by marcmengel** [comment]
In your defense, I believe there used to be a superclass one that interpolated the url= property of the packages class, but that seems not to work any more, at least for vx_y_z style versions...

**Pull request merged**
