### PR TITLE
add CAFAna package recipes

### PR DESCRIPTION
**Pull request by vhewes**
this PR adds package recipes for the OscLib and CAFAnaCore analysis packages, added here in the context of NOvA but also used by LAr experiments such as SBN and DUNE. i've also overhauled and cleaned up the `stan` and `stan-math` package recipes, which were a little hacked together and weren't working well out of the box.

i'm still working on finalizing the NOvA stack, so it's possible there will be more changes to these recipes at some point down the road, but i think they're mature enough to be propagated back into the main development branch.

### CODE REVIEW

**Review by gartung — APPROVED** [review]

**Comment by knoepfel** [comment]
@vhewes, thanks for the PR.  Because `cafana` and `osclib` are not supported by the SciSoft team (nor are they necessary dependencies of any SciSoft software), their recipes should be maintained in a separate repository.

Does NOvA rely on `stan` or `stan-math`?  The SciSoft team has recently removed those packages from the LArSoft and nulite distributions.

**Comment by vhewes** [comment]
@knoepfel yes, NOvA relies on `stan` and `stan-math` for MCMC fitting.

the reason i committed these analysis packages here is because they're shared between multiple experiments. if `fnal_art` is reserved *only* for SciSoft-supported packages, is there a different spack repo cutting across FNAL experiments that can be a home for package recipes that are collaboratively supported by the community or by multiple experiments? if not, i really think there needs to be one.

**Comment by knoepfel** [comment]
@vhewes, thanks your response.  We propose the following:

1. The `osclib` and `cafanacore` recipes should probably live in a repository in the [CAFAna GitHub organization](https://github.com/cafana/).  We are adopting a policy where a GitHub organization should include a repository of recipes for each body of software within that organization (this is true of `nusofthep-spack-recipes` and `larsoft-spack-recipes`).
2. We are willing to adopt the changes to `stan` and `stan-math` in the short term.  However, we would like to see these changes make it into upstream Spack as none of the software we develop relies on `stan` or `stan-math`.  Once those changes get included in upstream Spack, we can remove them from `fnal_art`.

Let us know if this proposal seems reasonable to you.

**Comment by knoepfel** [comment]
@vhewes, does [the above proposal](https://github.com/FNALssi/fnal_art/pull/90#issuecomment-2455512061) work for you?

**Comment by vhewes** [comment]
yes, the above works for me. if `osclib`/`cafanacore` are the only users of `stan-math` right now, then i'll just close out this PR and put all of those recipes in the cafana spack repo for the time being. i'll submit a PR to get the `stan` and `stan-math` packages into upstream spack, and that will be the long-term solution.

**Pull request closed without merging**
