### PR TITLE
Larbatch round2

### PR DESCRIPTION
**Pull request by marcmengel**
So just installing the Python files didn't give a working layout;
had to get the CMake bits working.

### CODE REVIEW

**Review by knoepfel — COMMENTED** [review]
@marcmengel, perhaps we should just the fix the `larbatch/CMakeLists.txt` file?  I know this doesn't fix the build for existing versions of `larbatch`, but if we don't do this, we have to start adding logic as to when we apply the patch.

**Comment by lgarren** [comment]
Um, Marc, why not use the latest larbatch, which has dropped cetbuildtools in favor of cetmodules.  The latest release is larbatch v01_59_04, which is currently in use by the larsoft distributions.   I don't understand why you're building this old release of larbatch.

**Comment by lgarren** [comment]
larbatch began using cetmodules in larbatch v01_57_00

**Comment by knoepfel** [comment]
@marcmengel, are you able to check if `larbatch` v01_57_00 can meet the need here?

**Comment by marcmengel** [comment]
I think so... should be in shortly..

**Comment by marcmengel** [comment]
Okay, I'm conufsed.  According to https://github.com/LArSoft/larbatch the latest tag is v1_51_15;  is there another repository that has v1_57_00?

**Comment by knoepfel** [comment]
Actually we have https://github.com/LArSoft/larbatch/tree/v01_59_04

**Comment by knoepfel** [comment]
Ah I see, it looks like`v01_51_15` was committed recently by @hgreenlee for MicroBooNE's production purposes.  The most up-to-date version of `larbatch`, however, is `v01_59_04`, and we should use that one.

**Comment by marcmengel** [comment]
Thanks, sorry I didn't look far enough back in the tags...

**Comment by marcmengel** [comment]
I've added 1.59.04, removed the cetbuildtools dependency, fixed the PYTHONPATH, and done a quick test install.

**Comment by knoepfel** [comment]
Looks good, @marcmengel.  Honestly, I'd be very tempted to drop support for `larbatch` 01.51.15 which, I believe, is used for a production system that only runs with UPS.  We could keep it in there for now, but I don't think it will ever be used.  Your call.

**Comment by marcmengel** [comment]
It installs, with a patch; we may as well keep it.

**Pull request merged**
