### PR TITLE
`fnal-github-package` mixin

### PR DESCRIPTION
**Pull request by knoepfel**
Mixin class intended to remove boilerplate code for GitHub-based packages.

### CODE REVIEW

**Comment by greenc-FNAL** [comment]
Nicely done @knoepfel!

Does `version_patterns` allow `spack versions <pkg>` to return useful results?

**Comment by knoepfel** [comment]
> Nicely done @knoepfel!
> 
> Does `version_patterns` allow `spack versions <pkg>` to return useful results?

For `art` we have:

```console
$ spack versions art
==> Safe versions (already checksummed):
  develop  3.14.03  3.14.01  3.13.02  3.12.00  3.10.00  3.09.03  3.05.00
  3.14.04  3.14.02  3.14.00  3.13.01  3.11.00  3.09.04  3.09.00  3.04.00
==> Remote versions (not yet checksummed):
  3_12_01  3_11_01
```

For `nutools`, where the tagging convention has changed from `vX_YY_ZZ` to `X.YY.ZZ`, only versions with the latter form are recognized (I think that's okay):

```console
$ spack versions nurandom
==> Safe versions (already checksummed):
  develop  1.11.04  1.10.02
==> Remote versions (not yet checksummed):
  1.11.03
```

**Comment by knoepfel** [comment]
@greenc-FNAL, I have:

- Removed the `utilities` package in favor of this one (`fnal-github-package`)
- Added a `@cmake_preset` decorator which, when decorating `def cmake_args(self)`, automatically adds the CMake preset arguments to the returned list
- Taken this PR out of draft mode.

I think more improvements can be made (such as possibly adding a `@sanitize_paths` decorator for the `setup_build_environment` and `setup_run_environment` methods), but I'd like more of your thoughts before going further.

**Comment by knoepfel** [comment]
I've now added a `@sanitize_paths` decorator that automatically calls `deprioritize_system_paths()` and `prune_duplicate_paths()` for each environment variable specified with `prepend_path(...)`.

**Pull request merged**
